// constants

export const enum EnvKey {
  JWT_SECRET = 'JWT_SECRET',
  COUCHBASE_HOST = 'COUCHBASE_HOST',
  COUCHBASE_USERNAME = 'COUCHBASE_USERNAME',
  COUCHBASE_PASSWORD = 'COUCHBASE_PASSWORD',
  COUCHBASE_BUCKET = 'COUCHBASE_BUCKET',
}
